name: First Workflow
on: workflow_dispatch    #manually trigger
jobs:
  first-job:
    runs-on: ubuntu-lates
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Done - bye"
